// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcLv3mBTPtN6-MOODEn4iAgZzPIrLvq5E',
    appId: '1:838039441032:web:0e61af00a6535cd928993d',
    messagingSenderId: '838039441032',
    projectId: 'techgranny',
    authDomain: 'techgranny.firebaseapp.com',
    storageBucket: 'techgranny.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGiH4mWhpZMmhR1X8gPhJh1OqHPFCjDcM',
    appId: '1:838039441032:android:864a972c99dee2d228993d',
    messagingSenderId: '838039441032',
    projectId: 'techgranny',
    storageBucket: 'techgranny.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD1J5iRrWqhxej9ob3CTf9wyH2JDN4Eto',
    appId: '1:838039441032:ios:8b0d838b90325c9f28993d',
    messagingSenderId: '838039441032',
    projectId: 'techgranny',
    storageBucket: 'techgranny.firebasestorage.app',
    iosBundleId: 'com.example.techgrannyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD1J5iRrWqhxej9ob3CTf9wyH2JDN4Eto',
    appId: '1:838039441032:ios:8b0d838b90325c9f28993d',
    messagingSenderId: '838039441032',
    projectId: 'techgranny',
    storageBucket: 'techgranny.firebasestorage.app',
    iosBundleId: 'com.example.techgrannyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcLv3mBTPtN6-MOODEn4iAgZzPIrLvq5E',
    appId: '1:838039441032:web:95d6f2fc3f2f84d928993d',
    messagingSenderId: '838039441032',
    projectId: 'techgranny',
    authDomain: 'techgranny.firebaseapp.com',
    storageBucket: 'techgranny.firebasestorage.app',
  );
}
